//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOMVIEW
    {
        public Nullable<int> REGNO_IN { get; set; }
        public string ODANO { get; set; }
        public string ODATIP { get; set; }
        public string YATAKTIP { get; set; }
        public string EVENT_SUBJECT { get; set; }
        public string KIRLI { get; set; }
        public string ARIZALI { get; set; }
        public string BLOKE { get; set; }
        public Nullable<decimal> FONTCOLOR { get; set; }
        public Nullable<decimal> ROOMCOLOR { get; set; }
        public Nullable<decimal> FLOOR { get; set; }
        public Nullable<decimal> SOLD { get; set; }
        public Nullable<decimal> CHDTOTAL { get; set; }
        public Nullable<decimal> NO { get; set; }
        public string ROOM { get; set; }
        public string TYPE { get; set; }
        public string RES_ROOM_TYPE { get; set; }
        public string BED { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string FROMTIME { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
        public string TOTIME { get; set; }
        public string LEAVETIME { get; set; }
        public string AGENCY { get; set; }
        public string AGENCY_SP_CODE { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public Nullable<decimal> GRUPNO { get; set; }
        public Nullable<System.DateTime> RELEASE { get; set; }
        public Nullable<System.DateTime> OPT { get; set; }
        public string TITLE { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string NAME { get; set; }
        public string FIRSTNAME2 { get; set; }
        public string LASTNAME2 { get; set; }
        public string BOARD { get; set; }
        public string PCODE { get; set; }
        public string STATE { get; set; }
        public string NATION { get; set; }
        public string SCODE1 { get; set; }
        public string SCODE2 { get; set; }
        public Nullable<decimal> SAFEKEY { get; set; }
        public Nullable<decimal> NROOM { get; set; }
        public Nullable<decimal> PAX { get; set; }
        public Nullable<decimal> EXTRA { get; set; }
        public Nullable<decimal> EXTRA2 { get; set; }
        public Nullable<decimal> CHD1 { get; set; }
        public Nullable<decimal> FREECHD1 { get; set; }
        public Nullable<decimal> CHD2 { get; set; }
        public Nullable<decimal> FREECHD2 { get; set; }
        public Nullable<decimal> BABY { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string STATUS_INFO { get; set; }
        public string REMARKREASON { get; set; }
        public string HOTELCODE { get; set; }
        public Nullable<decimal> ANLASMANO { get; set; }
        public Nullable<decimal> GOSHOW { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string VOCHER { get; set; }
        public string VIPTEXT { get; set; }
        public Nullable<decimal> VIPSTATUS { get; set; }
        public Nullable<decimal> COLOR { get; set; }
        public string STAY { get; set; }
        public Nullable<decimal> LOCK_ { get; set; }
        public string LOCKUSER_ { get; set; }
        public string LOCKREMARK_ { get; set; }
        public Nullable<decimal> WAITLIST { get; set; }
        public string WAITSTART { get; set; }
        public string WAITEND { get; set; }
        public string WAITREMARK { get; set; }
        public Nullable<decimal> STAYTYPE { get; set; }
        public string RESERVATIONCHANNEL { get; set; }
        public Nullable<decimal> SHADOW { get; set; }
        public Nullable<decimal> OCLIENTSTATUS { get; set; }
        public string EXTERNAL_IDENTIFIER { get; set; }
        public Nullable<decimal> EXTERNAL_SOURCE { get; set; }
        public string EXTERNAL_REMARK { get; set; }
        public Nullable<decimal> DEFINITE { get; set; }
        public Nullable<decimal> EXCLUDE_ALLOTMENT { get; set; }
        public string CONTRACT_NAME { get; set; }
        public Nullable<decimal> ALLOTMENT_ID { get; set; }
        public string ALLOTMENT_NAME { get; set; }
        public string GROUPNAME { get; set; }
        public Nullable<decimal> ACCOUNTTYPE { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string INVOICEID { get; set; }
        public Nullable<int> NIGHT { get; set; }
        public string ROOM_FEATURES { get; set; }
        public Nullable<decimal> PROFILEID { get; set; }
        public Nullable<decimal> SIDEBY { get; set; }
        public Nullable<decimal> MARKETCODE { get; set; }
        public Nullable<decimal> REGNO { get; set; }
        public string ACKOD { get; set; }
        public string PAX_INFO { get; set; }
        public Nullable<int> HKEEPCOLOR { get; set; }
        public Nullable<decimal> SHAREID { get; set; }
        public Nullable<decimal> SHAREMASTER { get; set; }
        public Nullable<int> SHARESLAVE { get; set; }
        public string MARKET { get; set; }
        public string C_COUT_TOTIME { get; set; }
        public Nullable<decimal> C_CIN_REGNO { get; set; }
        public string C_CIN_FROMTIME { get; set; }
        public string C_CIN_VIPTEXT { get; set; }
        public string C_CIN_LASTNAME { get; set; }
        public string C_CIN_FIRSTNAME { get; set; }
        public Nullable<decimal> C_CIN_PAX { get; set; }
        public Nullable<decimal> C_CIN_EXTRA { get; set; }
        public Nullable<decimal> C_CIN_CHD1 { get; set; }
        public Nullable<decimal> C_CIN_CHD2 { get; set; }
        public Nullable<decimal> C_CIN_BABY { get; set; }
        public string DIRTY { get; set; }
        public string OO { get; set; }
    }
}
