//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string CODE { get; set; }
        public Nullable<decimal> GROUPNO { get; set; }
        public string NAME { get; set; }
        public string PASSW { get; set; }
        public Nullable<decimal> LANG { get; set; }
        public string EMAIL { get; set; }
        public string POP3 { get; set; }
        public string SMTP { get; set; }
        public string EMAILUSER { get; set; }
        public string EMAILPASS { get; set; }
        public Nullable<decimal> DELETEONREAD { get; set; }
        public string PICTURE { get; set; }
        public string HOTELCODE { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> PROFILEID { get; set; }
        public Nullable<decimal> SHIFTID { get; set; }
        public Nullable<decimal> CASHIERID { get; set; }
        public Nullable<decimal> ROLEID { get; set; }
        public Nullable<decimal> REPORTROLEID { get; set; }
        public Nullable<decimal> INACTIVE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> LEAVEDATE { get; set; }
        public string INSURANCE { get; set; }
        public string DIRECTORY { get; set; }
        public Nullable<decimal> BADDNO { get; set; }
        public Nullable<decimal> EADDNO { get; set; }
        public Nullable<decimal> LASTADDNO { get; set; }
        public string REPORT_EMAIL { get; set; }
    }
}
